server:
  port: 8030
  servlet:
    context-path: /community

spring:
  application:
    name: forum-system

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.96.138:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456&
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 15 # \u8FDE\u63A5\u6C60\u6700\u5927\u7EBF\u7A0B\u6570
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  thymeleaf:
    cache: false

  mail:
    host: smtp.qq.com
    port: 465
    username: 2607687789@qq.com  # 最后提交需修改账号
    password: sroswaseznzyeaje
    protocol: smtps
    properties:
      smtp:
        ssl:
          enable: true

  redis:
    database: 11
    host: 192.168.96.133
    port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jmlee.community.entity
  configuration:
    use-generated-keys: true  # \u662F\u5426\u751F\u6210\u81EA\u589E\u4E3B\u952E\uFF0C\u9ED8\u8BA4\u4E3A false
    map-underscore-to-camel-case: true  # \u5B57\u6BB5\u662F\u5426\u533A\u5206\u5927\u5C0F\u5199\u4E14\u5C06\u4E0B\u5212\u7EBF\u548C\u9A7C\u5CF0\u547D\u540D\u6CD5\u81EA\u52A8\u5339\u914D\uFF0C\u9ED8\u8BA4 true



management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    # \u8BBE\u7F6EDao\u5C42\u7684\u65E5\u5FD7\u8F93\u51FA\u7EA7\u522B
    com.jmlee.community.dao: debug

# community global settings
community:
  path:
    domain: http://localhost:8030
    upload: F:/Java_Test/data/uploadData