server:
  port: 8030
  servlet:
    context-path: /community

spring:
  application:
    name: forum-system

  servlet:
    multipart:
      max-file-size: 100MB #设置单个文件大小
      max-request-size: 1000MB #设置总上传的数据大小

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.138.160:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ENC(9nktMQVh0Q+NNy9JF9r7+w==)
    password: ENC(/ND6+2HL7chivf0BuFLQUw==)
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 15 # \u8FDE\u63A5\u6C60\u6700\u5927\u7EBF\u7A0B\u6570
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  thymeleaf:
    cache: false



  mail:
    host: smtp.qq.com
    port: 465
    username: ENC(YEqqLDpPxtkhp1C+P4vansSfmtEmF9UX+seZVAN5qR8=)
    password: ENC(a0fxz0uyWuz2oNGz6UVFLld8A7YUg0KJGtGbEd8xLec=)
    protocol: smtps
    properties:
      smtp:
        ssl:
          enable: true

  redis:
    database: 11
    host: 192.168.138.160
    port: 6379
    timeout: 10000 # 连接超时时间
    lettuce:
      pool:
        max-active: 1024   # 最大连接数，默认是8
        max-wait: 10000    # 最大连接阻塞等待时间，默认是 -1
        max-idle: 200      # 最大空闲连接，默认是8
        min-idle: 5        # 最小空闲连接，默认是0

  kafka:
    bootstrap-servers: 192.168.138.160:9092 # 集群环境可配置多个，用逗号隔开
    consumer:
      group-id: community-consumer-group  # 指定一个默认分组
        # earliest:当各分区下存在已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
        # latest:当各分区下存在已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
        # none:topic各分区都存在已提交的offset时，从offset后开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 3000ms


  # 9300端口用于TCP连接，9200端口用于Http连接，后续es7.x已经不支持Tcp的方式进行连接，建议使用rest配置方式
  data:
    elasticsearch:
      cluster-name: my-es-cluster
      cluster-nodes: 192.168.138.160:9300
  elasticsearch:
    rest:
      uris: 192.168.138.160:9200

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jmlee.community.entity
  configuration:
    use-generated-keys: true  # 允许JDBC生成主键，默认为false
    map-underscore-to-camel-case: true  # 使用驼峰命名法转换字段，默认为true

jasypt:
  encryptor:
    password: jmlee**  # 根密码
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES


management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    # dao层日志输出级别，方便打印SQL语句
    com.jmlee.community.dao: debug

# community global settings
community:
  path:
    domain: http://localhost:8030
    upload: D:/Java_Test/data/upload-data

